# This workflow builds the client (UI), the server, builds the JAR.

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
   
  apriltag-build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
          - os: macos-latest
            artifact-name: macOS
          - os: ubuntu-latest
            artifact-name: Linux

    runs-on: ${{ matrix.os }}
    name: "Libapriltag - Build - ${{ matrix.artifact-name }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
        if: matrix.artifact-name != 'Win64'
      - run: |
          cmake -B build
          cmake --build build --config Release
        if: matrix.artifact-name == 'Win64'

      # Zip output to prevent name conflicts
      - run: zip -j libapriltag-${{ matrix.artifact-name }}.zip build/*.so build/*.dylib
        if: matrix.artifact-name != 'Win64'
      - run: Compress-Archive build/Release/*.dll libapriltag-${{ matrix.artifact-name }}.zip
        if: matrix.artifact-name == 'Win64'

      # Upload client artifact.
      - uses: actions/upload-artifact@master
        with:
          name: apriltag-${{ matrix.artifact-name }}
          path: libapriltag-${{ matrix.artifact-name }}.zip

  apriltag-build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: wpilib/roborio-cross-ubuntu:2022-18.04
            artifact-name: Athena
          - container: wpilib/raspbian-cross-ubuntu:10-18.04
            artifact-name: Raspbian
          - container: wpilib/aarch64-cross-ubuntu:bionic-18.04
            artifact-name: Aarch64

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    
    name: "Libapriltag - Build - ${{ matrix.artifact-name }}"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=CMake/arm-frc2022-linux-gnueabi.toolchain.cmake
          cmake --build build
        if: matrix.artifact-name == 'Athena'
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=CMake/arm-pi-gnueabihf.toolchain.cmake
          cmake --build build
        if: matrix.artifact-name == 'Raspbian'
      - run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=CMake/aarch64-bionic-linux-gnu.toolchain.cmake
          cmake --build build
        if: matrix.artifact-name == 'Aarch64'

      # Zip output to prevent name conflicts
      - name: "ZIP Output"
        run: zip -j libapriltag-${{ matrix.artifact-name }}.zip build/*.so
        
      # Upload client artifact.
      - uses: actions/upload-artifact@v3
        with:
          name: apriltag-${{ matrix.artifact-name }}
          path: libapriltag-${{ matrix.artifact-name }}.zip

  apriltag-release:
    needs: [apriltag-build-host, apriltag-build-docker]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            **/*.zip
